server:
  port: '@server.port@'

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint:
    health:
      show-details: always

info:
  version: '@project.version@'
  stage: dev

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  jpa:
    database: postgresql
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        default_schema: bukiper
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://changeit:5432/bukiper
    username: changeit
    password: changeit
  flyway:
    schemas: bukiper
    url: jdbc:postgresql://changeit:5432/bukiper
    user: changeit
    password: changeit

kafka:
  bootstrap-servers: changeit:9092
  consumer:
    group-id: bukiper
    concurrency: 7
  max-poll-records: 100
  max-poll-interval-ms: 60000
  max-session-timeout-ms: 60000
  ssl:
    enabled: false
    key-store-type: changeit
    key-store-location: changeit
    key-password: changeit
    trust-store-type: changeit
    trust-store-location: changeit
    trust-store-password: changeit
  topic:
    name: operation-log
    listener:
      enabled: false